// app/layout.jsx
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import Image from "next/image";
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers"; // <-- imported here

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Next.js Food Recipes",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/logo513.svg", type: "image/x-icon", sizes: "18x18" },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-screen bg-gradient-to-br from-orange-50 via-pink-30 to-amber-100 overflow-hidden">
          {/* Blurred Background Food Image */}
          <Image
            src="/sa11.jpg"
            alt="background"
            fill
            className="absolute left-6 top-0  w-full h-full object-cover opacity-30 blur-2xl pointer-events-none"
          />

          {/* Optional Glass Effect Box */}
          <div className="bg-white/30 backdrop-blur-lg border border-white/20 rounded-2xl"></div>

          {/* Wrap everything with Provider */}
          <Providers>
            <Nav />
            <Toaster />
            {children}
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  );
}
